# CSE 881 Project Data Preprocessing

## Cleaning and Data Exploration

In [69]:
#libraries
import pandas as pd
import numpy as np

In [70]:
#data

rankings=pd.read_csv("FIFA_Rankings.csv")
matches=pd.read_csv("world_cup_matches_scrape.csv")
full_gdp=pd.read_csv("WORLD_GDP_1960_PRESENT.csv", skiprows=3)
population=pd.read_csv("WORLD_POPULATION_1960_PRESENT.csv", skiprows=3)

In [71]:
rankings

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
0,1,Germany,GER,57.00,0.00,0,UEFA,1992-12-31
1,96,Syria,SYR,11.00,0.00,0,AFC,1992-12-31
2,97,Burkina Faso,BFA,11.00,0.00,0,CAF,1992-12-31
3,99,Latvia,LVA,10.00,0.00,0,UEFA,1992-12-31
4,100,Burundi,BDI,10.00,0.00,0,CAF,1992-12-31
...,...,...,...,...,...,...,...,...
64752,66,Cabo Verde,CPV,1354.65,1354.65,0,CAF,2023-07-20
64753,67,Iceland,ISL,1352.98,1352.98,0,UEFA,2023-07-20
64754,68,North Macedonia,MKD,1350.53,1350.53,0,UEFA,2023-07-20
64755,58,Jamaica,JAM,1409.73,1367.83,-5,CONCACAF,2023-07-20
64756,205,US Virgin Islands,VIR,816.59,816.59,-3,CONCACAF,2023-07-20

In [72]:
matches = pd.read_csv("world_cup_matches_scrape.csv")

#create match id
matches = matches.reset_index(drop=True)
matches["match_id"] = matches.index

matches

,year,stage,group,home_team,away_team,home_score,away_score,score_info,match_id
0,1930,Group Stage,Group 1,France,Mexico,4.0,1.0,NaN,0
1,1930,Group Stage,Group 1,Argentina,France,1.0,0.0,NaN,1
2,1930,Group Stage,Group 1,Chile,Mexico,3.0,0.0,NaN,2
3,1930,Group Stage,Group 1,Chile,France,1.0,0.0,NaN,3
4,1930,Group Stage,Group 1,Argentina,Mexico,6.0,3.0,NaN,4
...,...,...,...,...,...,...,...,...,...
924,2022,Quarterfinals,NaN,England,France,1.0,2.0,NaN,924
925,2022,Semifinals,NaN,Argentina,Croatia,3.0,0.0,NaN,925
926,2022,Semifinals,NaN,France,Morocco,2.0,0.0,NaN,926
927,2022,Third Place Match,NaN,Croatia,Morocco,2.0,1.0,NaN,927
928,2022,Final,NaN,Argentina,France,3.0,3.0,a.e.t.,928

In [73]:
full_gdp

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,...,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11,NaN,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.180769e+09,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,NaN,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,3.814488e+11,4.052607e+11,3.893300e+11,3.379747e+11,4.199863e+11,4.075960e+11,3.814407e+11,4.011450e+11,NaN,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,...,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,NaN,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,...,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,NaN,NaN

In [74]:
population

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,...,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,...,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,...,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,984846.0,1011421.0,1036950.0,1062737.0,1090270.0,1120168.0,...,1791019.0,1797086.0,1788891.0,1790151.0,1786079.0,1768096.0,1682668.0,1594353.0,NaN,NaN
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5532301.0,5655232.0,5782221.0,5911135.0,6048006.0,6195593.0,...,33090921.0,34085182.0,35111408.0,36134863.0,37140230.0,38222876.0,39390799.0,40583164.0,NaN,NaN
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16440172.0,16908035.0,17418522.0,17954564.0,18511361.0,19089380.0,...,57635162.0,58613001.0,59587885.0,60562381.0,61502603.0,62378410.0,63212384.0,64007187.0,NaN,NaN
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3153729.0,3254086.0,3358099.0,3465907.0,3577017.0,3692086.0,...,17441320.0,17973569.0,18513839.0,19059395.0,19603607.0,20152938.0,20723965.0,21314956.0,NaN,NaN
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3809389.0,3930401.0,4055959.0,4185877.0,4320006.0,4458462.0,...,14812482.0,15034452.0,15271368.0,15526888.0,15797210.0,16069056.0,16340822.0,16634373.0,NaN,NaN

In [75]:
#drop unwanted columns
gdp = full_gdp.drop(columns=["Unnamed: 70"])
pop = population.drop(columns=["Unnamed: 70"])

#convert long
gdp_long = gdp.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="GDP"
)

pop_long = pop.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Population"
)

#clean year
gdp_long["Year"] = gdp_long["Year"].astype(int)
pop_long["Year"] = pop_long["Year"].astype(int)

gdp_long = gdp_long.drop(columns=["Indicator Name", "Indicator Code", "Country Name"])
pop_long = pop_long.drop(columns=["Indicator Name", "Indicator Code", "Country Name"])

In [76]:
rankings["rank_date"] = pd.to_datetime(rankings["rank_date"])
rankings["Year"] = rankings["rank_date"].dt.year

#sort
rank = rankings.sort_values("rank_date")

#take first val
rank_clean = rank.groupby(
    ["country_abrv", "Year"],
    as_index=False
).first()

In [77]:
#build target
def get_result(row):
    if row["home_score"] > row["away_score"]:
        return 1   # home win
    elif row["home_score"] < row["away_score"]:
        return -1  # away win
    else:
        return 0   # draw

matches["result"] = matches.apply(get_result, axis=1)

#only keep certain features
matches = matches[[
    "match_id","year","stage", "home_team", "away_team", "home_score", "away_score", "result"
]]

In [78]:
country_map = gdp[["Country Name", "Country Code"]].drop_duplicates()

## Merging

In [79]:
#merge home
matches = matches.merge(
    country_map,
    left_on="home_team",
    right_on="Country Name",
    how="left"
).rename(columns={"Country Code": "home_code"}).drop(columns=["Country Name"])

#merge away
matches = matches.merge(
    country_map,
    left_on="away_team",
    right_on="Country Name",
    how="left"
).rename(columns={"Country Code": "away_code"}).drop(columns=["Country Name"])

print(len(matches))

929

In [80]:
#name mapping
country_fix = {
    "England": "GBR",
    "Scotland": "GBR",
    "Wales": "GBR",
    "Northern Ireland": "GBR",
    "United States": "USA",
    "South Korea": "KOR",
    "Iran": "IRN"
}

matches["home_code"] = matches["home_code"].fillna(
    matches["home_team"].map(country_fix)
)

matches["away_code"] = matches["away_code"].fillna(
    matches["away_team"].map(country_fix)
)

In [81]:
#merge home gdp
matches = matches.merge(
    gdp_long,
    left_on=["home_code", "year"],
    right_on=["Country Code", "Year"],
    how="left"
).rename(columns={"GDP": "home_gdp"}).drop(columns=["Country Code", "Year"])

#home pop
matches = matches.merge(
    pop_long,
    left_on=["home_code", "year"],
    right_on=["Country Code", "Year"],
    how="left"
).rename(columns={"Population": "home_pop"}).drop(columns=["Country Code", "Year"])

#merge away gdp
matches = matches.merge(
    gdp_long,
    left_on=["away_code", "year"],
    right_on=["Country Code", "Year"],
    how="left"
).rename(columns={"GDP": "away_gdp"}).drop(columns=["Country Code", "Year"])

#merge away pop
matches = matches.merge(
    pop_long,
    left_on=["away_code", "year"],
    right_on=["Country Code", "Year"],
    how="left"
).rename(columns={"Population": "away_pop"}).drop(columns=["Country Code", "Year"])

print(len(matches))

929

In [82]:
fifa_code_map = {
    "England": "ENG",
    "Scotland": "SCO",
    "Wales": "WAL",
    "Northern Ireland": "NIR",
    "United States": "USA",
    "South Korea": "KOR",
    "Iran": "IRN",
    "Algeria": "ALG",
    "Angola": "ANG",
    "Bulgaria": "BUL",
    "Chile": "CHI",
    "Costa Rica": "CRC",
    "Croatia": "CRO",
    "Czech Republic": "CZE",
    "Denmark": "DEN",
    "Egypt": "EGY",
    "FR Yugoslavia": "YUG",         
    "Germany": "GER",
    "Greece": "GRE",
    "Honduras": "HON",
    "Ivory Coast": "CIV",           
    "Netherlands": "NED",
    "North Korea": "PRK",
    "Paraguay": "PAR",
    "Portugal": "POR",
    "Republic of Ireland": "IRL",
    "Russia": "RUS",
    "Saudi Arabia": "KSA",
    "Serbia and Montenegro": "SCG", 
    "Slovakia": "SVK",
    "South Africa": "RSA",
    "Switzerland": "SUI",
    "Togo": "TOG",
    "Trinidad and Tobago": "TRI",
    "Turkey": "TUR",
    "Uruguay": "URU"
}

matches["home_fifa"] = matches["home_team"].map(fifa_code_map)
matches["away_fifa"] = matches["away_team"].map(fifa_code_map)

# fallback to existing codes where mapping not needed
matches["home_fifa"] = matches["home_fifa"].fillna(matches["home_code"])
matches["away_fifa"] = matches["away_fifa"].fillna(matches["away_code"])

In [83]:


matches = matches.merge(
    rank_clean,
    left_on=["home_fifa", "year"],
    right_on=["country_abrv", "Year"],
    how="left"
).rename(columns={"rank": "home_rank"}).drop(columns=["country_abrv", "Year"])

matches = matches.merge(
    rank_clean,
    left_on=["away_fifa", "year"],
    right_on=["country_abrv", "Year"],
    how="left"
).rename(columns={"rank": "away_rank"}).drop(columns=["country_abrv", "Year"])


print(len(matches))

929

In [84]:
#drop duplicates
matches = matches.loc[:, ~matches.columns.duplicated()]

#drop unwanted cols
matches = matches.drop(columns=[
    'country_full_x', 'total_points_x', 'previous_points_x',
    'rank_change_x', 'confederation_x', 'rank_date_x',
    'country_full_y', 'total_points_y', 'previous_points_y',
    'rank_change_y', 'confederation_y', 'rank_date_y'
], errors='ignore')

In [85]:
final_df = matches[[
    "match_id",
    "year",
    "stage",
    "home_team",
    "away_team",
    "home_score",
    "away_score",
    "home_rank",
    "away_rank",
    "home_gdp",
    "away_gdp",
    "home_pop",
    "away_pop",
    "result"
]]

In [86]:
final_df

,match_id,year,stage,home_team,away_team,home_score,away_score,home_rank,away_rank,home_gdp,away_gdp,home_pop,away_pop,result
0,0,1930,Group Stage,France,Mexico,4.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1,1930,Group Stage,Argentina,France,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2,1930,Group Stage,Chile,Mexico,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1
3,3,1930,Group Stage,Chile,France,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1
4,4,1930,Group Stage,Argentina,Mexico,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,924,2022,Quarterfinals,England,France,1.0,2.0,5.0,3.0,3.181244e+12,2.794788e+12,67604000.0,68184457.0,-1
925,925,2022,Semifinals,Argentina,Croatia,3.0,0.0,4.0,15.0,6.339938e+11,7.119650e+10,45407904.0,3855641.0,1
926,926,2022,Semifinals,France,Morocco,2.0,0.0,3.0,24.0,2.794788e+12,1.312453e+11,68184457.0,37329064.0,1
927,927,2022,Third Place Match,Croatia,Morocco,2.0,1.0,15.0,24.0,7.119650e+10,1.312453e+11,3855641.0,37329064.0,1
928,928,2022,Final,Argentina,France,3.0,3.0,4.0,3.0,6.339938e+11,2.794788e+12,45407904.0,68184457.0,0

In [87]:
#final_df.to_csv("cleaned_wc_matches.csv", index=False)

## Adding GDP and population data from Maddison Project

In [ ]:
wc=final_df

maddison = pd.read_csv("maddison_data.csv")
#filter
maddison = maddison[maddison["year"] >= 1920]

#scale pop
maddison["pop"] = maddison["pop"] * 1000

#construct gdp
maddison["gdp"] = maddison["gdppc"] * maddison["pop"]

#remove unwanted
maddison = maddison[["country", "year", "gdp", "pop"]]

In [ ]:
mapping = {
    "England": "United Kingdom",
    "Scotland": "United Kingdom",
    "Wales": "United Kingdom",
    "Northern Ireland": "United Kingdom",
    "West Germany": "Germany",
    "East Germany": "Germany",
    "Soviet Union": "Russian Federation",
    "Yugoslavia": "Serbia",
    "FR Yugoslavia": "Serbia",
    "Serbia and Montenegro": "Serbia",
    "Czechoslovakia": "Czech Republic",
    "Republic of Ireland": "Ireland",
    "South Korea": "Republic of Korea",
    "North Korea": "D.P.R. of Korea",
    "Iran": "Iran (Islamic Republic of)",
    "Ivory Coast": "Côte d'Ivoire",
    "Zaire": "D.R. of the Congo",
    "Dutch East Indies": "Indonesia",
    "Bolivia": "Bolivia (Plurinational State of)",
    "Russia": "Russian Federation",
    "Yugoslavia": "Former Yugoslavia",
    "Soviet Union": "Former USSR",
}

wc["home_team_mapped"] = wc["home_team"].replace(mapping)
wc["away_team_mapped"] = wc["away_team"].replace(mapping)

/var/folders/d7/7k64ck4x6s3fzvn9phwlvzmh0000gn/T/ipykernel_67168/3290869728.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wc["home_team_mapped"] = wc["home_team"].replace(mapping)
/var/folders/d7/7k64ck4x6s3fzvn9phwlvzmh0000gn/T/ipykernel_67168/3290869728.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wc["away_team_mapped"] = wc["away_team"].replace(mapping)

In [90]:
wc = wc.drop(columns=[
    "home_gdp", "away_gdp",
    "home_pop", "away_pop"
], errors="ignore")

wc["year"] = wc["year"].astype(int)
maddison["year"] = maddison["year"].astype(int)

In [91]:
wc = wc.merge(
    maddison,
    left_on=["home_team_mapped", "year"],
    right_on=["country", "year"],
    how="left"
)

wc = wc.rename(columns={
    "gdp": "home_gdp",
    "pop": "home_pop"
}).drop(columns=["country"])

wc = wc.merge(
    maddison,
    left_on=["away_team_mapped", "year"],
    right_on=["country", "year"],
    how="left"
)

wc = wc.rename(columns={
    "gdp": "away_gdp",
    "pop": "away_pop"
}).drop(columns=["country"])

wc = wc.drop(columns=["home_team_mapped", "away_team_mapped"])

In [94]:
print("Home GDP missing:", wc["home_gdp"].isna().mean())
print("Away GDP missing:", wc["away_gdp"].isna().mean())

print("Home Pop missing:", wc["home_pop"].isna().mean())
print("Away Pop missing:", wc["away_pop"].isna().mean())
wc

Home GDP missing: 0.010764262648008612
Away GDP missing: 0.017222820236813777
Home Pop missing: 0.004305705059203444
Away Pop missing: 0.004305705059203444

,match_id,year,stage,home_team,away_team,home_score,away_score,home_rank,away_rank,result,home_gdp,home_pop,away_gdp,away_pop
0,0,1930,Group Stage,France,Mexico,4.0,1.0,NaN,NaN,1,3.005906e+11,41610000.0,3.835178e+10,17175000.0
1,1,1930,Group Stage,Argentina,France,1.0,0.0,NaN,NaN,1,7.735969e+10,11896000.0,3.005906e+11,41610000.0
2,2,1930,Group Stage,Chile,Mexico,3.0,0.0,NaN,NaN,1,2.080102e+10,4266000.0,3.835178e+10,17175000.0
3,3,1930,Group Stage,Chile,France,1.0,0.0,NaN,NaN,1,2.080102e+10,4266000.0,3.005906e+11,41610000.0
4,4,1930,Group Stage,Argentina,Mexico,6.0,3.0,NaN,NaN,1,7.735969e+10,11896000.0,3.835178e+10,17175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,924,2022,Quarterfinals,England,France,1.0,2.0,5.0,3.0,-1,2.615231e+12,68093380.0,2.671569e+12,68386540.0
925,925,2022,Semifinals,Argentina,Croatia,3.0,0.0,4.0,15.0,1,8.549143e+11,46736250.0,1.022846e+11,3790180.0
926,926,2022,Semifinals,France,Morocco,2.0,0.0,3.0,24.0,1,2.671569e+12,68386540.0,3.116550e+11,37101220.0
927,927,2022,Third Place Match,Croatia,Morocco,2.0,1.0,15.0,24.0,1,1.022846e+11,3790180.0,3.116550e+11,37101220.0
928,928,2022,Final,Argentina,France,3.0,3.0,4.0,3.0,0,8.549143e+11,46736250.0,2.671569e+12,68386540.0

In [93]:
#wc.to_csv("wc_match_data.csv", index=False)